# Github 레포지토리 Actions 페이지에 나타나는 이름
name: Upload Docker Image to ECR & Pull Image to Beanstalk

# event trigger
on:
  push:
    branches: [develop] # 추후 main으로 수정

jobs:
  deploy:
    name: Deploy mucal-backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      ## jdk setting
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      ## gradle caching -> 빌드 시간 빨라짐
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |  
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
              
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mucal-demo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"

      ## Gradle build를 통해 만들어진 JAR를 beanstalk에 배포하기 위해 ZIP 파일로 만들기
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp -r .ebextensions deploy/.ebextensions
          cp Dockerrun.aws.json deploy/Dockerrun.aws.json # Elastic Beanstalk에서 Docker 실행 시 체크하는 설정 파일
          cd deploy && zip -r deploy.zip .
      
      ## Beanstalk Deploy 플러그
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mu-cal-app
          environment_name: Mucalapp-env-1
          version_label: mucal-backend-docker-${{steps.current-time.outputs.formattedTime}} # 배포 버전 타임스탬프로 구분
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 200
